export enum IconName {
  Address = 'address',
  ArrowRight = 'arrowRight',
  Checkmark = 'checkmark',
  DeliveryAndService = 'deliveryAndService',
  Download = 'download',
  Durability = 'durability',
  Efficiency = 'efficiency',
  Email = 'email',
  IrrigationFeature1 = 'irrigationFeature1',
  IrrigationFeature2 = 'irrigationFeature2',
  IrrigationFeature3 = 'irrigationFeature3',
  IrrigationFeature4 = 'irrigationFeature4',
  Offers = 'offers',
  Partnership = 'partnership',
  Support = 'support',
  Phone = 'phone',
}
